shellEmulator: true

trustPolicy: no-downgrade

packages:
  - core
  - docs
  - play
catalog:
  '@antfu/eslint-config': 7.2.0
  '@dcloudio/types': 3.4.29
  '@uni-helper/uni-types': 1.0.0-alpha.7
  '@vue/shared': 3.4.21
  '@vue/tsconfig': 0.8.1
  eslint: 9.39.2
  eslint-plugin-format: 1.3.1
  jiti: 2.6.1
  less: 4.5.1
  rimraf: 6.1.2
  typescript: 5.9.3
  vite: 5.4.21
  vitest: 4.0.17
  vue: 3.4.21
