shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'vite@5.4.21'
  - '@vitejs/plugin-legacy@5.3.2'
  - 'detect-port@1.6.1'
  - 'chokidar@4.0.3'
  - 'semver@5.7.2 || 6.3.1'
  - 'synckit@0.9.3'

packages:
  - ui

catalog:
  '@ant-design/colors': '8.0.1'
  '@ant-design/fast-color': '3.0.1'
  '@dcloudio/uni-app': '3.0.0-4080720251210001'
  '@dcloudio/uni-app-harmony': '3.0.0-4080720251210001'
  '@dcloudio/uni-app-plus': '3.0.0-4080720251210001'
  '@dcloudio/uni-components': '3.0.0-4080720251210001'
  '@dcloudio/uni-h5': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-alipay': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-baidu': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-harmony': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-jd': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-kuaishou': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-lark': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-qq': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-toutiao': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-weixin': '3.0.0-4080720251210001'
  '@dcloudio/uni-mp-xhs': '3.0.0-4080720251210001'
  '@dcloudio/uni-quickapp-webview': '3.0.0-4080720251210001'
  'enum-plus': '3.1.7'
  'pinia': '3.0.4'
  'vue': '3.4.21'
  'vue-router': '4.5.1'
  '@dcloudio/types': '3.4.29'
  '@dcloudio/uni-automator': '3.0.0-4080720251210001'
  '@dcloudio/uni-cli-shared': '3.0.0-4080720251210001'
  '@dcloudio/uni-stacktracey': '3.0.0-4080720251210001'
  '@dcloudio/uni-vue-devtools': '3.0.0-4080720251210001'
  '@dcloudio/vite-plugin-uni': '3.0.0-4080720251210001'
  '@ianvs/prettier-plugin-sort-imports': '4.7.0'
  '@tsconfig/node22': '22.0.5'
  '@types/wechat-miniprogram': '3.4.10'
  '@uni-helper/plugin-uni': '0.1.0'
  '@uni-helper/uni-env': '0.2.0'
  '@uni-helper/uni-types': '1.0.0-alpha.7'
  '@uni-helper/unocss-preset-uni': '0.2.11'
  '@uni-helper/vite-plugin-uni-components': '0.2.6'
  '@uni-helper/vite-plugin-uni-manifest': '0.2.12'
  '@uni-helper/vite-plugin-uni-pages': '0.3.23'
  '@uni-ku/bundle-optimizer': '2.1.0'
  '@uni-ku/root': '1.4.1'
  '@unocss/eslint-config': '65.4.3'
  '@unocss/preset-legacy-compat': '65.4.3'
  '@vitejs/plugin-vue': '6.0.3'
  '@vue/eslint-config-prettier': '10.2.0'
  '@vue/eslint-config-typescript': '14.6.0'
  '@vue/runtime-core': '3.4.21'
  '@vue/shared': '3.4.21'
  '@vue/tsconfig': '0.8.1'
  'chalk': '5.6.2'
  'consola': '3.4.2'
  'eslint': '9.39.2'
  'eslint-plugin-vue': '10.7.0'
  'eslint-plugin-yml': '3.0.0'
  'globals': '17.1.0'
  'husky': '9.1.7'
  'jiti': '2.6.1'
  'less': '4.5.1'
  'lint-staged': '16.2.7'
  'npm-run-all2': '8.0.4'
  'ora': '8.2.0'
  'prettier': '3.8.1'
  'sort-package-json': '3.6.1'
  'typescript': '5.9.3'
  'unocss': '65.4.3'
  'unocss-applet': '0.12.2'
  'unplugin-auto-import': '21.0.0'
  'vite': '5.4.21'
  'vite-plugin-compression2': '2.4.0'
  'vue-component-type-helpers': '3.2.4'
  'vue-tsc': '3.2.4'
